# ***Resume Classification***

# ***Business objective:***


The document classification solution should significantly reduce the manual human effort in the HRM. It should achieve a higher level of accuracy and automation with minimal human intervention.

# ***1) Import Libraries***

In [ ]:
# We install pdf2docx because there is one pdf file in React Developer folder so we need to convert that file into .docx.
!pip install pdf2docx
# We install textract to extract text data.
!pip install textract

Requirement already satisfied: pdf2docx in /usr/local/lib/python3.10/dist-packages (0.5.6)
Requirement already satisfied: PyMuPDF>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (1.22.5)
Requirement already satisfied: python-docx>=0.8.10 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (0.8.11)
Requirement already satisfied: fonttools>=4.24.0 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (4.41.0)
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (1.22.4)
Requirement already satisfied: opencv-python>=4.5 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (4.7.0.72)
Requirement already satisfied: fire>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from pdf2docx) (0.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.3.0->pdf2docx) (1.12.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.3.0->pdf2docx) (2.3.0)
Requirement already satisfied: lxml>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from python-docx>=0.8.10->pdf2docx) (4.9.3)
Requirement already satisfied: textract in /usr/local/lib/python3.10/dist-packages (1.6.5)
Requirement already satisfied: argcomplete~=1.10.0 in /usr/local/lib/python3.10/dist-packages (from textract) (1.10.3)
Requirement already satisfied: beautifulsoup4~=4.8.0 in /usr/local/lib/python3.10/dist-packages (from textract) (4.8.2)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.10/dist-packages (from textract) (3.0.4)
Requirement already satisfied: docx2txt~=0.8 in /usr/local/lib/python3.10/dist-packages (from textract) (0.8)
Requirement already satisfied: extract-msg<=0.29.* in /usr/local/lib/python3.10/dist-packages (from textract) (0.28.7)
Requirement already satisfied: pdfminer.six==20191110 in /usr/local/lib/python3.10/dist-packages (from textract) (20191110)
Requirement already satisfied: python-pptx~=0.6.18 in /usr/local/lib/python3.10/dist-packages (from textract) (0.6.21)
Requirement already satisfied: six~=1.12.0 in /usr/local/lib/python3.10/dist-packages (from textract) (1.12.0)
Requirement already satisfied: SpeechRecognition~=3.8.1 in /usr/local/lib/python3.10/dist-packages (from textract) (3.8.1)
Requirement already satisfied: xlrd~=1.2.0 in /usr/local/lib/python3.10/dist-packages (from textract) (1.2.0)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20191110->textract) (3.18.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20191110->textract) (2.4.0)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4~=4.8.0->textract) (2.4.1)
Requirement already satisfied: imapclient==2.1.0 in /usr/local/lib/python3.10/dist-packages (from extract-msg<=0.29.*->textract) (2.1.0)
Requirement already satisfied: olefile>=0.46 in /usr/local/lib/python3.10/dist-packages (from extract-msg<=0.29.*->textract) (0.46)
Requirement already satisfied: tzlocal>=2.1 in /usr/local/lib/python3.10/dist-packages (from extract-msg<=0.29.*->textract) (5.0.1)
Requirement already satisfied: compressed-rtf>=1.0.6 in /usr/local/lib/python3.10/dist-packages (from extract-msg<=0.29.*->textract) (1.0.6)
Requirement already satisfied: ebcdic>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from extract-msg<=0.29.*->textract) (1.1.1)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-pptx~=0.6.18->textract) (4.9.3)
Requirement already satisfied: Pillow>=3.3.2 in /usr/local/lib/python3.10/dist-packages (from python-pptx~=0.6.18->textract) (8.4.0)
Requirement already satisfied: XlsxWriter>=0.5.7 in /usr/local/lib/python3.10/dist-packages (from python-pptx~=0.6.18->textract) (3.1.2)

In [ ]:
import os
import textract
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Import all resume files.
!git clone https://github.com/Himanshupatil9723/Dataset.git

fatal: destination path 'Dataset' already exists and is not an empty directory.

In [ ]:
os.listdir('/content/Dataset/Resumes')

['workday resumes',
 'SQL Developer Lightning insight',
 'React Developer',
 'Peoplesoft resumes']

# ***2. Exctract the Text from Dataset***

In [ ]:
#Create filepath and category for Peoplesoft resume folder.
file_path1 = []
category1  = []
directory1 = '/content/Dataset/Resumes/Peoplesoft resumes'
for i in os.listdir(directory1):
    if i.endswith('.docx'):
        os.path.join(directory1, i)
        file_path1.append((textract.process(os.path.join(directory1, i))).decode('utf-8'))
        category1.append('PeopleSoft')

In [ ]:
#Create datafarame for Peoplesoft Resume folder
data1 = pd.DataFrame(data = file_path1 , columns = ['Raw_Details'])
data1['Category1'] = category1
data1

                                          Raw_Details   Category1
0   C O N T A C T :\n\n\n\nAddress: Manyata Tech P...  PeopleSoft
1   Vinod Akkala                                  ...  PeopleSoft
2   Rahul Ahuja\n\n-------------------------------...  PeopleSoft
3   Hari Narayana \t\t              \n\n\t\n\n\n\n...  PeopleSoft
4   PeopleSoft Administration\n\n \n\nVivekanand S...  PeopleSoft
5   PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...  PeopleSoft
6   Priyanka Ramadoss\n\n\t61/46, MountPleasant, \...  PeopleSoft
7   PeopleSoft Database Administrator\n\n         ...  PeopleSoft
8   Personal Details\t\t\n\n\n\nName\n\nPritam Bis...  PeopleSoft
9   Arun Venu\n\n\n\n\t  EXPERIENCE SUMMARY\t\n\n\...  PeopleSoft
10  SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...  PeopleSoft
11  G. Ananda Rayudu \n\n\t\t       https://www.li...  PeopleSoft
12  PeopleSoft Admin/PeopleSoft DBA\n\n\n\nGanesh ...  PeopleSoft
13  R Ahmed                                       ...  PeopleSoft
14  Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...  PeopleSoft
15  Murali\t\t       \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...  PeopleSoft
16  PEOPLESOFT Administrator\n\n\n\n\n\nSRINIVAS.K...  PeopleSoft
17  Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...  PeopleSoft
18  Classification: Internal\n\nClassification: In...  PeopleSoft
19  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...  PeopleSoft

In [ ]:
from pdf2docx import Converter

path_input = '/content/Dataset/Resumes/React Developer'
path_output = '/content/Dataset/Resumes/React Developer'

In [ ]:
#Convert one PDF file to .docx.
for file in os.listdir(path_input):
    if file.endswith('.pdf'):
        final = os.path.join(path_input, file)
        cv = Converter(final)
        basename = os.path.splitext(file)[0]
        print(basename)
        cv.convert(path_output + '/' + basename+'.docx', start=0, end=None)
        cv.close()

Reactjs Developer_Prabakaran_Musquare Technologies

In [ ]:
#Create filepath and category for React Developer folder.
file_path2 = []
category2  = []
directory2 = '/content/Dataset/Resumes/React Developer'
for i in os.listdir(directory2):
    if i.endswith('.docx'):
        os.path.join(directory2, i)
        file_path2.append((textract.process(os.path.join(directory2, i))).decode('utf-8'))
        category2.append('React Developer')

In [ ]:
#Create datafarame for React Developer folder
data2 = pd.DataFrame(data = file_path2 , columns = ['Raw_Details'])
data2['Category2'] = category2
data2

                                          Raw_Details        Category2
0   SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...  React Developer
1   Maryala Vinay Reddy\n\n\n\n\tProfessional Summ...  React Developer
2   Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...  React Developer
3   Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...  React Developer
4   SHAIK ABDUL SHARUK   \n\n2 years’ Experience i...  React Developer
5   KAMALAKAR REDDY. A \n\nLinked In: https://www....  React Developer
6   MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n   ...  React Developer
7   Naveen Sadhu\n\n\n\n\n\nTitle: software develo...  React Developer
8   Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...  React Developer
9   Ranga Gaganam  \n\n\n\n \n\nProfessional\n\n \...  React Developer
10  Ui-Developer/ React JS Developer \n\nNAME: KRI...  React Developer
11  KAMBALA SAI SURENDRA   \n\n \n\n \n\n \n\n\n\n...  React Developer
12  Name: Ravali P \n\n\n\n                       ...  React Developer
13  PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...  React Developer
14  SUSOVAN  BAG   \n\nSeeking  a  challenging  po...  React Developer
15  CURRICULUM VITAE\n\n\n\n\n\n\n\nAnjani Priyada...  React Developer
16  MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...  React Developer
17  Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...  React Developer
18  Venkatalakshmi Pedireddy\n\nSoftware Developer...  React Developer
19  HARIPRIYA BATTINA \n\nExperience as UI Develop...  React Developer
20  MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...  React Developer
21  FULLSTACK SOFTWARE DEVELOPER / WEB DEVELOPER\n...  React Developer
22  Name: M. Prabakaran \nTitle: UI Developer\n\nP...  React Developer
23  Ui-Developer/ React JS Developer \n\nNAME: KRI...  React Developer

In [ ]:
#Create filepath and category for SQL Developer Lightning insight folder.
file_path3 = []
category3  = []
directory3 = '/content/Dataset/Resumes/SQL Developer Lightning insight'
for i in os.listdir(directory3):
    if i.endswith('.docx'):
        os.path.join(directory3, i)
        file_path3.append((textract.process(os.path.join(directory3, i))).decode('utf-8'))
        category3.append('SQL Developer')

In [ ]:
#Create datafarame for SQL Developer Lightning insight folder
data3 = pd.DataFrame(data = file_path3 , columns = ['Raw_Details'])
data3['Category3'] = category3
data3

                                          Raw_Details      Category3
0   Resume\n\nName     :  Neeraj Mishra\n\n\n\nExp...  SQL Developer
1   BUDDHA VAMSI                                  ...  SQL Developer
2   SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...  SQL Developer
3   KAMBALLA PRADEEP                              ...  SQL Developer
4   SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...  SQL Developer
5   ANIL KUMAR MADDUKURI  \t\t\n\nSQL & MSBI Devel...  SQL Developer
6   Tatikonda Kiran Kumar.\n\n\n\n\n\n\n\n\t\tCare...  SQL Developer
7   Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...  SQL Developer
8   Aradhana Tripathi\n\n\n\nCurrent Location: Gac...  SQL Developer
9   SQL SERVER DEVELOPER\n\n\n\n\n\nPriyanka L    ...  SQL Developer
10  resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...  SQL Developer
11  RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...  SQL Developer
12  SQL DEVELOPER\n\nName: -   Bandi prem sai\n\n\...  SQL Developer
13   Hyderabad\n\n\nNazeer Basha\n\nSQL and Power...  SQL Developer

In [ ]:
#Create filepath and category for workday resumes folder.
file_path4 = []
category4  = []
directory4 = '/content/Dataset/Resumes/workday resumes'
for i in os.listdir(directory4):
    if i.endswith('.docx'):
        os.path.join(directory4, i)
        file_path4.append((textract.process(os.path.join(directory4, i))).decode('utf-8'))
        category4.append('Workday')

In [ ]:
#Create datafarame for workday resumes folder
data4 = pd.DataFrame(data = file_path4 , columns = ['Raw_Details'])
data4['Category4'] = category4
data4

                                          Raw_Details Category4
0   Workday Integration Consultant\n\n\n\nName    ...   Workday
1   Madeeswar A\n\n\t\n\n\t\t\n\n\t\t\tPROFILE SUM...   Workday
2   Name\t: Naresh Babu Cherukuri\n\n\n\nObjective...   Workday
3   WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...   Workday
4   Name         : Gopi Krishna Reddy\n\n\t\t\t\t ...   Workday
5   Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...   Workday
6   HIMA.MENDU\n\n\t  \n\n\n\nCareer Objective\n\n...   Workday
7   Workday HCM  Techno functional Consultant     ...   Workday
8   Mooraboyina Guravaiah\n\nWorkday Integration S...   Workday
9   G Himaja\n\n                                  ...   Workday
10  JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...   Workday
11  Hari Krishna M\n\n\n\n\n\nSummary:\n\nA result...   Workday
12  Punugoti Swetha\n\nWorkday Technical Consultan...   Workday
13  Name:\tJ. Sumanth Royal.\n\n\t\n\nPROFESSIONAL...   Workday
14  Shireesh Balasani                             ...   Workday
15  Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...   Workday
16  Harikrishna Akula                             ...   Workday
17  Vinay kumar .v\nWorkday Functional Consultant\...   Workday
18  Srikanth (WORKDAY hCM Consultant)\t           ...   Workday
19  VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...   Workday
20  Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...   Workday

# ***3. Create a Resume DataFrame***

In [ ]:
#Create resume dataframe which contains all four folder data.
resume_data = data1.append([data2, data3, data4], ignore_index = True)
resume_data

,Raw_Details,Category1,Category2,Category3,Category4
0,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,PeopleSoft,NaN,NaN,NaN
1,Vinod Akkala ...,PeopleSoft,NaN,NaN,NaN
2,Rahul Ahuja\n\n-------------------------------...,PeopleSoft,NaN,NaN,NaN
3,Hari Narayana \t\t \n\n\t\n\n\n\n...,PeopleSoft,NaN,NaN,NaN
4,PeopleSoft Administration\n\n \n\nVivekanand S...,PeopleSoft,NaN,NaN,NaN
...,...,...,...,...,...
74,Harikrishna Akula ...,NaN,NaN,NaN,Workday
75,Vinay kumar .v\nWorkday Functional Consultant\...,NaN,NaN,NaN,Workday
76,Srikanth (WORKDAY hCM Consultant)\t ...,NaN,NaN,NaN,Workday
77,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,NaN,NaN,NaN,Workday
78,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,NaN,NaN,NaN,Workday

In [ ]:
resume_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Raw_Details  79 non-null     object
 1   Category1    20 non-null     object
 2   Category2    24 non-null     object
 3   Category3    14 non-null     object
 4   Category4    21 non-null     object
dtypes: object(5)
memory usage: 3.2+ KB

In [ ]:
#Create final Category column for all resumes.
resume_data['Category'] = category1 + category2 + category3 + category4
resume_data

,Raw_Details,Category1,Category2,Category3,Category4,Category
0,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
1,Vinod Akkala ...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
2,Rahul Ahuja\n\n-------------------------------...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
3,Hari Narayana \t\t \n\n\t\n\n\n\n...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
4,PeopleSoft Administration\n\n \n\nVivekanand S...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
...,...,...,...,...,...,...
74,Harikrishna Akula ...,NaN,NaN,NaN,Workday,Workday
75,Vinay kumar .v\nWorkday Functional Consultant\...,NaN,NaN,NaN,Workday,Workday
76,Srikanth (WORKDAY hCM Consultant)\t ...,NaN,NaN,NaN,Workday,Workday
77,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,NaN,NaN,NaN,Workday,Workday
78,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,NaN,NaN,NaN,Workday,Workday

In [ ]:
#Drop Category1, Category2,Category3 & Category4 columns
resume_data.drop(['Category1', 'Category2', 'Category3', 'Category4'], axis = 1, inplace = True)
resume_data = resume_data[["Category", "Raw_Details"]]
#Create final dataset which contains raw_details and Resume Category.

In [ ]:
#Final Dataframe
resume_data

      Category                                        Raw_Details
0   PeopleSoft  C O N T A C T :\n\n\n\nAddress: Manyata Tech P...
1   PeopleSoft  Vinod Akkala                                  ...
2   PeopleSoft  Rahul Ahuja\n\n-------------------------------...
3   PeopleSoft  Hari Narayana \t\t              \n\n\t\n\n\n\n...
4   PeopleSoft  PeopleSoft Administration\n\n \n\nVivekanand S...
..         ...                                                ...
74     Workday  Harikrishna Akula                             ...
75     Workday  Vinay kumar .v\nWorkday Functional Consultant\...
76     Workday  Srikanth (WORKDAY hCM Consultant)\t           ...
77     Workday  VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...
78     Workday  Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...

[79 rows x 2 columns]

In [ ]:
resume_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Category     79 non-null     object
 1   Raw_Details  79 non-null     object
dtypes: object(2)
memory usage: 1.4+ KB